name: Deploy Infrastructure

# Ogni volta che viene eseguito un push sul ramo main
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**' # Solo se ci sono cambiamenti nella cartella terraform

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    
    steps:
      # 1. Scarico il codice
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Installo Terraform nel server di GitHub
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # 3. Configuro le credenziali AWS (i.e. Secrets)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      # 4. Inizializzo Terraform
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # 5. Applica le modifiche (Auto-approve salta la richiesta di "yes")
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve